name: Deploy Vite React App to Hostinger

on:
  push:
    branches:
      - master # Change this to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies and deploy
        env:
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
          FTP_SERVER: ${{ secrets.FTP_SERVER }}
        run: |
          bash deploy.sh



# name: Deploy Vite React App to Hostinger

# on:
#   push:
#     branches:
#       - main # Change this to your main branch name

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Install dependencies and deploy
#         env:
#           FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
#           FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
#           FTP_SERVER: ${{ secrets.FTP_SERVER }}
#         run: |
#           bash deploy.sh
